### PR TITLE
Add service worker controlled pages report

### PR DESCRIPTION
**Pull request by tomayac**
Breaking down https://github.com/HTTPArchive/httparchive.org/pull/51 into small PRs, this is the second.

### CODE REVIEW

**Comment by tomayac** [comment]
This is dependent on https://github.com/HTTPArchive/bigquery/pull/62.

**Comment by rviscomi** [comment]
Does this PR contain all of the same changes from #74? I'll wait to review this until that one is merged and this PR is synced.

**Comment by tomayac** [comment]
@rviscomi PTAL, merged 'master' into my branch. This should be good to go now.

- Also, the colors match:
  screen shot 2018-08-28 at 08 44 24
- Graphics:
   screen shot 2018-08-28 at 08 48 39

**Comment by rviscomi** [comment]
👍 Can you run `npm run deploy` to make these changes live?

**Comment by tomayac** [comment]
Thanks for the merge. We're [live](https://httparchive.org/reports/progressive-web-apps?lens=wordpress&start=2017_08_01&end=latest&view=list) 🎉.

**Pull request merged**
