### PR TITLE
Clarify setup steps

### PR DESCRIPTION
**Pull request by tomayac**

### CODE REVIEW

**Comment by rviscomi** [comment]
@tomayac not sure if this change is necessary. doesn't gcloud ask you to switch projects?

**Comment by tomayac** [comment]
> doesn't gcloud ask you to switch projects?

FWIW, it didn't. The problem was hidden in the error message:
```
$ npm run start

> httparchive.org@0.0.1 start /Users/tsteiner/Documents/node/httparchive.org
> npm run watch & python main.py


> httparchive.org@0.0.1 watch /Users/tsteiner/Documents/node/httparchive.org
> webpack --config webpack.config.js --watch

/Users/tsteiner/Documents/node/httparchive.org/env/lib/python2.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Webpack is watching the files…

Traceback (most recent call last):
  File "main.py", line 22, in <module>
    import reports as report_util
  File "/Users/tsteiner/Documents/node/httparchive.org/reports.py", line 35, in <module>
    update_reports()
  File "/Users/tsteiner/Documents/node/httparchive.org/reports.py", line 30, in update_reports
    report_dates = dateutil.get_dates()
  File "/Users/tsteiner/Documents/node/httparchive.org/dates.py", line 7, in get_dates
    gcs = storage.Client()
  File "/Users/tsteiner/Documents/node/httparchive.org/env/lib/python2.7/site-packages/google/cloud/storage/client.py", line 71, in __init__
    _http=_http)
  File "/Users/tsteiner/Documents/node/httparchive.org/env/lib/python2.7/site-packages/google/cloud/client.py", line 215, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/Users/tsteiner/Documents/node/httparchive.org/env/lib/python2.7/site-packages/google/cloud/client.py", line 171, in __init__
    raise EnvironmentError('Project was not passed and could not be '
EnvironmentError: Project was not passed and could not be determined from the environment.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! httparchive.org@0.0.1 start: `npm run watch & python main.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the httparchive.org@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tsteiner/.npm/_logs/2018-07-10T12_04_00_348Z-debug.log
```

**Comment by rviscomi** [comment]
Let's change this setup step to combine both authentication and project selection into the single `init` command.

@tomayac can you change the heading to `4. Initialize the Google Cloud CLI:` and the code sample to `gcloud init`?

**Comment by tomayac** [comment]
@rviscomi PTAL.

**Comment by rviscomi** [comment]
Thanks @tomayac!

**Pull request merged**
