### PR TITLE
Grid view

### LINKED ISSUE #70: Enable a grid view of metrics
By default the view of report pages is to vertically list all metrics. Each metric has:

- title
- description
- optional "See also" for other reports
- visualization
- data table toggle button
- data table

All of this UI baggage may make it difficult to skim through the report to get an overall sense for how things are going.

The purpose of this feature request is to design a **grid view** of metrics so that only the necessary information to understand the state of the metrics is shown compactly.

### PR DESCRIPTION
**Pull request by rviscomi**
Closes #70 

Features:
- new toggle buttons in the permalink form
  - selecting a button will set the `view` URL param, eg `view=grid`
- loading the page with the `view` URL param will set it as the default view
- reports may specify their default view in the JSON config
  - a user-specified view will overwrite the default view, eg report default is grid but user passes `view=list`, then list view will be used
- responsive CSS grid design
  - 3 cols on desktop, 2 on tablet, 1 on mobile
- expand/collapse toggle button on each metric
  - visible by default on mobile or when metric is expanded
  - expand appears on hover over the metric
- metrics in the URL hash will be expanded by default when entering grid view

Demo the grid view on the staging server: https://staging.httparchive.org/reports/page-weight?view=grid

View toggle button:
image

Grid view:
image

Expand/collapse toggle button:
image

Expanded grid view:
image

### CODE REVIEW

**Comment by igrigorik** [comment]
This is awesome! In terms of functionality, can't +1 this strongly enough. 

In terms of design — disclaimer, I'm no designer — I think we can clean this up a little bit to provide some visual separation to make it easier to chunk and process visually. Here's a quick attempt...

image

Just playing in DevTools, half of these are garbage..
image

- outline the boxes
- decrease font size to create more clear visual hierarchy

**Comment by rviscomi** [comment]
I like it! Thanks for the suggestions. Pushed a commit and redeployed to the staging server. Here's my version:

desktop (3 cols)
image

tablet (2 cols)
image

mobile (1 col)
image

**Comment by igrigorik** [comment]
Yay! :)

I like the [] icon for the expand, but WDYT of also having the title toggle that? Right now, you can click on the title to update the anchor, but could it also toggle the open/close?

**Comment by rviscomi** [comment]
Yeah I like that suggestion! Pushed a commit and the changes are deploying to staging now (will be up in ~5 mins)

**Comment by igrigorik** [comment]
Hmm, should be live by now, right? Doesn't seem to work on this end (did a hard refresh).

**Comment by rviscomi** [comment]
Oh dear. I did a full deploy rather than a staging deploy :open_mouth: 

Go ahead and demo the changes at https://httparchive.org/reports/state-of-the-web?view=grid and I can push again with any feedback changes.

**Comment by igrigorik** [comment]
Ah, hehe. Looks great! Ship it.. err, I guess it already is? :)

**Pull request merged**
